SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS]
@RELATORIO INTEGER = NULL
AS 
SET NOCOUNT ON; 
BEGIN 

IF @RELATORIO = 99999
BEGIN 

DECLARE @QTDE_REG_TB1 INTEGER = 0
DECLARE @QTDE_REG_TB2 INTEGER = 0

DROP TABLE IF EXISTS FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01;

CREATE TABLE FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01 (
NUMERO_CONSULTA INTEGER NOT NULL,
DESCRICAO_CONSULTA VARCHAR (100) NOT NULL,
INFOR_DADOS NVARCHAR(40) NOT NULL
);

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_116_PR_ENTRADAS_CREDITOS_SAIDAS_NAO_TRIBUTADAS_ITENS_PARA_ANALISE') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_116_PR_ENTRADAS_CREDITOS_SAIDAS_NAO_TRIBUTADAS_ITENS_PARA_ANALISE)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 116, '116_PR_ENTRADAS_CREDITOS_SAIDAS_NAO_TRIBUTADAS_ITENS_PARA_ANALISE','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE
BEGIN 
INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 116, '116_PR_ENTRADAS_CREDITOS_SAIDAS_NAO_TRIBUTADAS_ITENS_PARA_ANALISE','CONSULTA CONTEM DADOS PARA ANALISE' ;

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 117, '117_PR_ENTRADAS_CREDITOS_SAIDAS_NAO_TRIBUTADAS_EXTRACAO_ITENS_SELECIONADOS','CONSULTA CONTEM DADOS PARA ANALISE' ;
END

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 116, '116_PR_ENTRADAS_CREDITOS_SAIDAS_NAO_TRIBUTADAS_ITENS_PARA_ANALISE','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_138_PR_SAIDAS_ITENS_PARA_ANALISE') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_138_PR_SAIDAS_ITENS_PARA_ANALISE)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 138, '138_PR_SAIDAS_ITENS_PARA_ANALISE','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE
BEGIN 
INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 138, '138_PR_SAIDAS_ITENS_PARA_ANALISE','CONSULTA CONTEM DADOS PARA ANALISE' ;

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 139, '139_PR_SAIDAS_EXTRACAO_ITENS_SELECIONADOS','CONSULTA CONTEM DADOS PARA ANALISE' ;
END

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 138, '138_PR_SAIDAS_ITENS_PARA_ANALISE','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_157_PR_APURACAO_VALOR_RECOLHIMENTO_MINIMO_ATACADISTA_TARE_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_157_PR_APURACAO_VALOR_RECOLHIMENTO_MINIMO_ATACADISTA_TARE_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 157, '157_PR_APURACAO_VALOR_RECOLHIMENTO_MINIMO_ATACADISTA_TARE_01','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 157, '157_PR_APURACAO_VALOR_RECOLHIMENTO_MINIMO_ATACADISTA_TARE_01',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 157, '157_PR_APURACAO_VALOR_RECOLHIMENTO_MINIMO_ATACADISTA_TARE_01','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_112_PR_ENTRADAS_LANCADAS_COM_CREDITO_A_MAIOR_C190_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_112_PR_ENTRADAS_LANCADAS_COM_CREDITO_A_MAIOR_C190_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 112, '112_PR_ENTRADAS_LANCADAS_COM_CREDITO_A_MAIOR_C190','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 112, '112_PR_ENTRADAS_LANCADAS_COM_CREDITO_A_MAIOR_C190',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 112, '112_PR_ENTRADAS_LANCADAS_COM_CREDITO_A_MAIOR_C190','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_125_PR_ENTRADAS_CREDITO_E111_ICMS_GARANTIDO_CONFRONTO_PAGAMENTO_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_125_PR_ENTRADAS_CREDITO_E111_ICMS_GARANTIDO_CONFRONTO_PAGAMENTO_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 125, '125_PR_ENTRADAS_CREDITO_E111_ICMS_GARANTIDO_CONFRONTO_PAGAMENTO','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 125, '125_PR_ENTRADAS_CREDITO_E111_ICMS_GARANTIDO_CONFRONTO_PAGAMENTO',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 125, '125_PR_ENTRADAS_CREDITO_E111_ICMS_GARANTIDO_CONFRONTO_PAGAMENTO','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_126_PR_ENTRADAS_CREDITO_C190_CFOP_SUBST_TRIBUT_MERCADORIAS_REVENDA_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_126_PR_ENTRADAS_CREDITO_C190_CFOP_SUBST_TRIBUT_MERCADORIAS_REVENDA_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 126, '126_PR_ENTRADAS_CREDITO_C190_CFOP_SUBST_TRIBUT_MERCADORIAS_REVENDA','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 126, '126_PR_ENTRADAS_CREDITO_C190_CFOP_SUBST_TRIBUT_MERCADORIAS_REVENDA',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 125, '126_PR_ENTRADAS_CREDITO_C190_CFOP_SUBST_TRIBUT_MERCADORIAS_REVENDA','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_113_PR_ENTRADAS_NOTA_CANCELADA_LANCADA_COMO_AUTORIZADA_C100_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_113_PR_ENTRADAS_NOTA_CANCELADA_LANCADA_COMO_AUTORIZADA_C100_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 113, '113_PR_ENTRADAS_NOTA_CANCELADA_LANCADA_COMO_AUTORIZADA_C100','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 113, '113_PR_ENTRADAS_NOTA_CANCELADA_LANCADA_COMO_AUTORIZADA_C100',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 113, '113_PR_ENTRADAS_NOTA_CANCELADA_LANCADA_COMO_AUTORIZADA_C100','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_114_PR_ENTRADAS_NOTAS_LANCADAS_MAIS_DE_UM_PERIODO_REGISTRO_C100_02') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_114_PR_ENTRADAS_NOTAS_LANCADAS_MAIS_DE_UM_PERIODO_REGISTRO_C100_02)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 114, '114_PR_ENTRADAS_NOTAS_LANCADAS_MAIS_DE_UM_PERIODO_REGISTRO_C100','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 114, '114_PR_ENTRADAS_NOTAS_LANCADAS_MAIS_DE_UM_PERIODO_REGISTRO_C100',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 114, '114_PR_ENTRADAS_NOTAS_LANCADAS_MAIS_DE_UM_PERIODO_REGISTRO_C100','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_101_PR_AUSENCIA_APRESENTACAO_EFD_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_101_PR_AUSENCIA_APRESENTACAO_EFD_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 101, '101_PR_AUSENCIA_APRESENTACAO_EFD','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 101, '101_PR_AUSENCIA_APRESENTACAO_EFD', 'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 101, '101_PR_AUSENCIA_APRESENTACAO_EFD','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_111_PR_ENTRADAS_LANCADAS_C100_VALOR_CONTABIL_A_MENOR_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_111_PR_ENTRADAS_LANCADAS_C100_VALOR_CONTABIL_A_MENOR_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 111, '111_PR_ENTRADAS_LANCADAS_C100_VALOR_CONTABIL_A_MENOR','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 111, '111_PR_ENTRADAS_LANCADAS_C100_VALOR_CONTABIL_A_MENOR',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 111, '111_PR_ENTRADAS_LANCADAS_C100_VALOR_CONTABIL_A_MENOR','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_134_PR_SAIDAS_LANCADAS_C190_COM_DEBITO_A_MENOR_ICMS_03') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_134_PR_SAIDAS_LANCADAS_C190_COM_DEBITO_A_MENOR_ICMS_03)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 134, '134_PR_SAIDAS_LANCADAS_C190_COM_DEBITO_A_MENOR_ICMS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 134, '134_PR_SAIDAS_LANCADAS_C190_COM_DEBITO_A_MENOR_ICMS',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 134, '134_PR_SAIDAS_LANCADAS_C190_COM_DEBITO_A_MENOR_ICMS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_137_PR_SAIDAS_AUTORIZADAS_LANCADAS_CANCELADAS_C100_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_137_PR_SAIDAS_AUTORIZADAS_LANCADAS_CANCELADAS_C100_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 137, '137_PR_SAIDAS_AUTORIZADAS_LANCADAS_CANCELADAS_C100','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 137, '137_PR_SAIDAS_AUTORIZADAS_LANCADAS_CANCELADAS_C100',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 137, '137_PR_SAIDAS_AUTORIZADAS_LANCADAS_CANCELADAS_C100','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_102_PR_AUSENCIA_SEQUENCIAL_DENTRO_SERIE_NFCE_02') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_102_PR_AUSENCIA_SEQUENCIAL_DENTRO_SERIE_NFCE_02)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 102, '102_PR_AUSENCIA_SEQUENCIAL_DENTRO_SERIE_NFCE','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 102, '102_PR_AUSENCIA_SEQUENCIAL_DENTRO_SERIE_NFCE', 'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 102, '102_PR_AUSENCIA_SEQUENCIAL_DENTRO_SERIE_NFCE','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_103_PR_AUSENCIA_SEQUENCIAL_DENTRO_SERIE_NFE_02') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_103_PR_AUSENCIA_SEQUENCIAL_DENTRO_SERIE_NFE_02)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 103, '103_PR_AUSENCIA_SEQUENCIAL_DENTRO_SERIE_NFE','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 103, '103_PR_AUSENCIA_SEQUENCIAL_DENTRO_SERIE_NFE', 'CONSULTA CONTEM DADOS PARA ANALISE';

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 103, '103_PR_AUSENCIA_SEQUENCIAL_DENTRO_SERIE_NFE','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_171_PR_FALTA_LANC_OU_DIVERG_NF_EFD_ACESSORIA_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_171_PR_FALTA_LANC_OU_DIVERG_NF_EFD_ACESSORIA_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 171, '171_PR_FALTA_LANC_OU_DIVERG_NF_EFD_ACESSORIA','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 171, '171_PR_FALTA_LANC_OU_DIVERG_NF_EFD_ACESSORIA', 'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 171, '171_PR_FALTA_LANC_OU_DIVERG_NF_EFD_ACESSORIA','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_172_PR_FALTA_LANC_NF_EFD_OBRIGACAO_PRINCIPAL_ENTRADAS_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_172_PR_FALTA_LANC_NF_EFD_OBRIGACAO_PRINCIPAL_ENTRADAS_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 172, '172_PR_FALTA_LANC_NF_EFD_OBRIGACAO_PRINCIPAL_ENTRADAS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 172, '172_PR_FALTA_LANC_NF_EFD_OBRIGACAO_PRINCIPAL_ENTRADAS', 'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 172, '172_PR_FALTA_LANC_NF_EFD_OBRIGACAO_PRINCIPAL_ENTRADAS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_173_PR_FALTA_LANC_NF_EFD_OBRIGACAO_PRINCIPAL_SAIDAS_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_173_PR_FALTA_LANC_NF_EFD_OBRIGACAO_PRINCIPAL_SAIDAS_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 173, '173_PR_FALTA_LANC_NF_EFD_OBRIGACAO_PRINCIPAL_SAIDAS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 173, '173_PR_FALTA_LANC_NF_EFD_OBRIGACAO_PRINCIPAL_SAIDAS', 'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 173, '173_PR_FALTA_LANC_NF_EFD_OBRIGACAO_PRINCIPAL_SAIDAS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_151_PR_APURACAO_DIVERGENCIA_TRANSPORTE_DEBITOS_CREDITOS_DO_E111_PARA_E110_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (
SELECT COUNT(*) 
FROM FISC.TB_151_PR_APURACAO_DIVERGENCIA_TRANSPORTE_DEBITOS_CREDITOS_DO_E111_PARA_E110_01 
WHERE DIF_VL_TOT_AJ_DEBITOS <> '-' OR DIF_VL_ESTORNOS_CRED <> '-' OR DIF_VL_TOT_AJ_CREDITOS <> '-' OR DIF_VL_ESTORNOS_DEB <> '-'
)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 151, '151_PR_APURACAO_DIVERGENCIA_TRANSPORTE_DEBITOS_CREDITOS_DO_E111_PARA_E110','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 151, '151_PR_APURACAO_DIVERGENCIA_TRANSPORTE_DEBITOS_CREDITOS_DO_E111_PARA_E110',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 151, '151_PR_APURACAO_DIVERGENCIA_TRANSPORTE_DEBITOS_CREDITOS_DO_E111_PARA_E110','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_152_PR_APURACAO_DIVERGENCIA_TRANSPORTE_SALDO_CREDOR_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (
SELECT COUNT(*) 
FROM FISC.TB_152_PR_APURACAO_DIVERGENCIA_TRANSPORTE_SALDO_CREDOR_01
WHERE VL_CALC_SALDO_CREDOR_TRANSP_A_MAIOR <> '0.00'
)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 152, '152_PR_APURACAO_DIVERGENCIA_TRANSPORTE_SALDO_CREDOR','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 152, '152_PR_APURACAO_DIVERGENCIA_TRANSPORTE_SALDO_CREDOR',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 152, '152_PR_APURACAO_DIVERGENCIA_TRANSPORTE_SALDO_CREDOR','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_153_PR_APURACAO_DIVERGENCIA_TRANSPORTE_VALOR_DO_ICMS_DAS_ENTRADAS_SAIDAS_PARA_E110_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (
SELECT COUNT(*) 
FROM FISC.TB_153_PR_APURACAO_DIVERGENCIA_TRANSPORTE_VALOR_DO_ICMS_DAS_ENTRADAS_SAIDAS_PARA_E110_01
WHERE ALERTA_CREDITOS <> '-' OR ALERTA_DEBITOS <> '-'
)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 153, '153_PR_APURACAO_DIVERGENCIA_TRANSPORTE_VALOR_DO_ICMS_DAS_ENTRADAS_SAIDAS_PARA_E110','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 153, '153_PR_APURACAO_DIVERGENCIA_TRANSPORTE_VALOR_DO_ICMS_DAS_ENTRADAS_SAIDAS_PARA_E110',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 153, '153_PR_APURACAO_DIVERGENCIA_TRANSPORTE_VALOR_DO_ICMS_DAS_ENTRADAS_SAIDAS_PARA_E110','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_154_PR_APURACAO_REG_CREDITOS_CIAP_E111_SEM_INFORMACAO_BLOCO_G_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_154_PR_APURACAO_REG_CREDITOS_CIAP_E111_SEM_INFORMACAO_BLOCO_G_02 WHERE ALERTA_CIAP = 'POSSIVEL CREDITO DO CIAP')

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 154, '154_PR_APURACAO_REG_CREDITOS_CIAP_E111_SEM_INFORMACAO_BLOCO_G','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 154, '154_PR_APURACAO_REG_CREDITOS_CIAP_E111_SEM_INFORMACAO_BLOCO_G',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 154, '154_PR_APURACAO_REG_CREDITOS_CIAP_E111_SEM_INFORMACAO_BLOCO_G','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_156_PR_APURACAO_CREDITO_FAIN_SALDO_CREDOR_CONTA_CORRENTE_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_156_PR_APURACAO_CREDITO_FAIN_SALDO_CREDOR_CONTA_CORRENTE_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 156, '156_PR_APURACAO_CREDITO_FAIN_SALDO_CREDOR_CONTA_CORRENTE','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 156, '156_PR_APURACAO_CREDITO_FAIN_SALDO_CREDOR_CONTA_CORRENTE',  'CONSULTA CONTEM DADOS PARA ANALISE';

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 156, '156_PR_APURACAO_CREDITO_FAIN_SALDO_CREDOR_CONTA_CORRENTE','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_133_PR_SAIDAS_DESTINADAS_PESSOA_FISICA_COM_POSSIBILIDADE_DE_VINCULACAO_A_EMPRESA_NA_PARAIBA_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_133_PR_SAIDAS_DESTINADAS_PESSOA_FISICA_COM_POSSIBILIDADE_DE_VINCULACAO_A_EMPRESA_NA_PARAIBA_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 133, '133_PR_SAIDAS_DESTINADAS_PESSOA_FISICA_COM_POSSIBILIDADE_DE_VINCULACAO_A_EMPRESA_NA_PARAIBA','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 133, '133_PR_SAIDAS_DESTINADAS_PESSOA_FISICA_COM_POSSIBILIDADE_DE_VINCULACAO_A_EMPRESA_NA_PARAIBA', 'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 133, '133_PR_SAIDAS_DESTINADAS_PESSOA_FISICA_COM_POSSIBILIDADE_DE_VINCULACAO_A_EMPRESA_NA_PARAIBA','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_135_PR_SAIDAS_LANCADAS_VALOR_CONTABIL_A_MAIOR_C100_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_135_PR_SAIDAS_LANCADAS_VALOR_CONTABIL_A_MAIOR_C100_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 135, '135_PR_SAIDAS_LANCADAS_VALOR_CONTABIL_A_MAIOR_C100','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 135, '135_PR_SAIDAS_LANCADAS_VALOR_CONTABIL_A_MAIOR_C100',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 135, '135_PR_SAIDAS_LANCADAS_VALOR_CONTABIL_A_MAIOR_C100','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_136_PR_SAIDAS_USO_ALIQUOTA_INTERESTADUAL_EM_OPERACAO_INTERNA_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_136_PR_SAIDAS_USO_ALIQUOTA_INTERESTADUAL_EM_OPERACAO_INTERNA_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 136, '136_PR_SAIDAS_USO_ALIQUOTA_INTERESTADUAL_EM_OPERACAO_INTERNA','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 136, '136_PR_SAIDAS_USO_ALIQUOTA_INTERESTADUAL_EM_OPERACAO_INTERNA',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 136, '136_PR_SAIDAS_USO_ALIQUOTA_INTERESTADUAL_EM_OPERACAO_INTERNA','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_119_PR_ENTRADAS_CREDITO_CTE_FRETE_CIF_SOBRE_NF_SAIDAS_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_119_PR_ENTRADAS_CREDITO_CTE_FRETE_CIF_SOBRE_NF_SAIDAS_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 119, '119_PR_ENTRADAS_CREDITO_CTE_FRETE_CIF_SOBRE_NF_SAIDAS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 119, '119_PR_ENTRADAS_CREDITO_CTE_FRETE_CIF_SOBRE_NF_SAIDAS',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 119, '119_PR_ENTRADAS_CREDITO_CTE_FRETE_CIF_SOBRE_NF_SAIDAS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_120_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPR_TERCEIR_SUBST_TRIB_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_120_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPR_TERCEIR_SUBST_TRIB_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 120, '120_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPR_TERCEIR_SUBST_TRIB','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 120, '120_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPR_TERCEIR_SUBST_TRIB',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 120, '120_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPR_TERCEIR_SUBST_TRIB','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO_01') AND 
TYPE IN (N'U'))
BEGIN 

 IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_121_PR_ENTRADAS_CREDITO_CTE_TOMADOR_FRETE_OUTRO_CONTRIBUINTE_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_121_PR_ENTRADAS_CREDITO_CTE_TOMADOR_FRETE_OUTRO_CONTRIBUINTE_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 121, '121_PR_ENTRADAS_CREDITO_CTE_TOMADOR_FRETE_OUTRO_CONTRIBUINTE','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 121, '121_PR_ENTRADAS_CREDITO_CTE_TOMADOR_FRETE_OUTRO_CONTRIBUINTE',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 121, '121_PR_ENTRADAS_CREDITO_CTE_TOMADOR_FRETE_OUTRO_CONTRIBUINTE','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_122_PR_ENTRADAS_CREDITO_CTE_LANCADAS_COM_CREDITO_A_MAIOR_D190_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_122_PR_ENTRADAS_CREDITO_CTE_LANCADAS_COM_CREDITO_A_MAIOR_D190_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 122, '122_PR_ENTRADAS_CREDITO_CTE_LANCADAS_COM_CREDITO_A_MAIOR_D190','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 122, '122_PR_ENTRADAS_CREDITO_CTE_LANCADAS_COM_CREDITO_A_MAIOR_D190',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 122, '122_PR_ENTRADAS_CREDITO_CTE_LANCADAS_COM_CREDITO_A_MAIOR_D190','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_123_PR_ENTRADAS_CREDITO_CTE_CANCELADO_LANCADO_AUTORIZADO_D100_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_123_PR_ENTRADAS_CREDITO_CTE_CANCELADO_LANCADO_AUTORIZADO_D100_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 123, '123_PR_ENTRADAS_CREDITO_CTE_CANCELADO_LANCADO_AUTORIZADO_D100','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 123, '123_PR_ENTRADAS_CREDITO_CTE_CANCELADO_LANCADO_AUTORIZADO_D100',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 123, '123_PR_ENTRADAS_CREDITO_CTE_CANCELADO_LANCADO_AUTORIZADO_D100','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_141_PR_SAIDAS_CTE_LANCADOS_D190_COM_DEBITO_A_MENOR_ICMS_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_141_PR_SAIDAS_CTE_LANCADOS_D190_COM_DEBITO_A_MENOR_ICMS_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 141, '141_PR_SAIDAS_CTE_LANCADOS_D190_COM_DEBITO_A_MENOR_ICMS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 141, '141_PR_SAIDAS_CTE_LANCADOS_D190_COM_DEBITO_A_MENOR_ICMS',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 141, '141_PR_SAIDAS_CTE_LANCADOS_D190_COM_DEBITO_A_MENOR_ICMS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_142_PR_SAIDA_CTE_AUTORIZADO_LANCADO_CANCELADO_D100_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_142_PR_SAIDA_CTE_AUTORIZADO_LANCADO_CANCELADO_D100_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 142, '142_PR_SAIDA_CTE_AUTORIZADO_LANCADO_CANCELADO_D100','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 142, '142_PR_SAIDA_CTE_AUTORIZADO_LANCADO_CANCELADO_D100',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 142, '142_PR_SAIDA_CTE_AUTORIZADO_LANCADO_CANCELADO_D100','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_143_PR_SAIDA_SUCATA_PARA_INDUSTRIA_PAGAMENTO_ICMS_DIFERIDO_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_143_PR_SAIDA_SUCATA_PARA_INDUSTRIA_PAGAMENTO_ICMS_DIFERIDO_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 143, '143_PR_SAIDA_SUCATA_PARA_INDUSTRIA_PAGAMENTO_ICMS_DIFERIDO','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 143, '143_PR_SAIDA_SUCATA_PARA_INDUSTRIA_PAGAMENTO_ICMS_DIFERIDO',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 143, '143_PR_SAIDA_SUCATA_PARA_INDUSTRIA_PAGAMENTO_ICMS_DIFERIDO','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_144_PR_SAIDA_SUCATA_PARA_OUTRA_UF_PAGAMENTO_ICMS_DIFERIDO_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_144_PR_SAIDA_SUCATA_PARA_OUTRA_UF_PAGAMENTO_ICMS_DIFERIDO_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 144, '144_PR_SAIDA_SUCATA_PARA_OUTRA_UF_PAGAMENTO_ICMS_DIFERIDO','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 144, '144_PR_SAIDA_SUCATA_PARA_OUTRA_UF_PAGAMENTO_ICMS_DIFERIDO',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 144, '144_PR_SAIDA_SUCATA_PARA_OUTRA_UF_PAGAMENTO_ICMS_DIFERIDO','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_174_PR_FALTA_LANC_CTE_D100_OBRIGACAO_PRINCIPAL_SAIDAS_01') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_174_PR_FALTA_LANC_CTE_D100_OBRIGACAO_PRINCIPAL_SAIDAS_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 174, '174_PR_FALTA_LANC_CTE_D100_OBRIGACAO_PRINCIPAL_SAIDAS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 174, '174_PR_FALTA_LANC_CTE_D100_OBRIGACAO_PRINCIPAL_SAIDAS',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 174, '174_PR_FALTA_LANC_CTE_D100_OBRIGACAO_PRINCIPAL_SAIDAS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO_02') AND 
 TYPE IN (N'U'))
 BEGIN 

 SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO_01)
 SET @QTDE_REG_TB2 = (SELECT COUNT(*) FROM FISC.TB_115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO_02)

 IF @QTDE_REG_TB1 + @QTDE_REG_TB2 = 0

 INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
 SELECT 115, '115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO','CONSULTA NAO CONTEM DADOS PARA ANALISE' ; 

 ELSE 

 INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
 SELECT 115, '115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

 END

 ELSE 

 BEGIN 

 SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO_01)

 IF @QTDE_REG_TB1 = 0

 INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
 SELECT 115, '115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

 ELSE 

 INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
 SELECT 115, '115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO',  'CONSULTA CONTEM DADOS PARA ANALISE';
 
 END

END
ELSE
BEGIN 

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO_02') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB2 = (SELECT COUNT(*) FROM FISC.TB_115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO_02)

IF @QTDE_REG_TB2 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 115, '115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 115, '115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 115, '115_PR_ENTRADAS_APROPRIACAO_CREDITO_INDEVIDO_USO_CONS_A_FIXO','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

END

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS_01') AND 
TYPE IN (N'U'))
BEGIN 

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS_02') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS_01)
SET @QTDE_REG_TB2 = (SELECT COUNT(*) FROM FISC.TB_118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS_02)

IF @QTDE_REG_TB1 + @QTDE_REG_TB2 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 118, '118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 118, '118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS',  'CONSULTA CONTEM DADOS PARA ANALISE';

END
ELSE
BEGIN 

SET @QTDE_REG_TB1 = (SELECT COUNT(*) FROM FISC.TB_118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS_01)

IF @QTDE_REG_TB1 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 118, '118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 118, '118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS',  'CONSULTA CONTEM DADOS PARA ANALISE';

END
END

ELSE
BEGIN 

IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS_02') AND 
TYPE IN (N'U'))
BEGIN 

SET @QTDE_REG_TB2 = (SELECT COUNT(*) FROM FISC.TB_118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS_02)

IF @QTDE_REG_TB2 = 0

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 118, '118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

ELSE 

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 118, '118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS',  'CONSULTA CONTEM DADOS PARA ANALISE' ;

END

ELSE

INSERT INTO FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
SELECT 118, '118_PR_ENTRADAS_CREDITO_CTE_COM_ITENS_NFE_PROPRIA_TERCEIROS','CONSULTA NAO CONTEM DADOS PARA ANALISE' ;

END

END

IF @RELATORIO IS NULL
BEGIN 
IF EXISTS (SELECT NAME FROM SYS.OBJECTS  WHERE  OBJECT_ID = OBJECT_ID(N'FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01') AND 
TYPE IN (N'U'))

SELECT NUMERO_CONSULTA,DESCRICAO_CONSULTA,INFOR_DADOS
FROM FISC.TB_100_PR_SUMARIO_DADOS_CONSULTAS_INCONSISTENCIAS_01
ORDER BY NUMERO_CONSULTA

END;

END
GO
