SELECT fisc.TB_201_PR_XML_NOTAS_FISCAIS_PROPRIAS_E_TERCEIROS_01.NF_CPF_CNPJ_EMITENTE, fisc.TB_217_PR_XML_CTE_PROPRIOS_E_TERCEIROS_VINCULADO_A_NFE_02.CTE_CPF_CNPJ_TOMADOR, 
             fisc.TB_201_PR_XML_NOTAS_FISCAIS_PROPRIAS_E_TERCEIROS_01.NF_SITUACAO, fisc.TB_201_PR_XML_NOTAS_FISCAIS_PROPRIAS_E_TERCEIROS_01.NF_CHAVE_ACESSO, 
             fisc.TB_201_PR_XML_NOTAS_FISCAIS_PROPRIAS_E_TERCEIROS_01.NF_CPF_CNPJ_DESTINATARIO, fisc.TB_217_PR_XML_CTE_PROPRIOS_E_TERCEIROS_VINCULADO_A_NFE_02.CTE_CPF_CNPJ_EMIT, 
             fisc.TB_217_PR_XML_CTE_PROPRIOS_E_TERCEIROS_VINCULADO_A_NFE_02.CTE_UF_EMIT, fisc.TB_217_PR_XML_CTE_PROPRIOS_E_TERCEIROS_VINCULADO_A_NFE_02.CTE_CHCTE, 
             fisc.TB_217_PR_XML_CTE_PROPRIOS_E_TERCEIROS_VINCULADO_A_NFE_02.CTE_SITUACAO, fisc.TB_PAGAMENTOS_TRANSPORTAROS_OUTRAS_UF.Valor_ICMS
FROM   fisc.TB_217_PR_XML_CTE_PROPRIOS_E_TERCEIROS_VINCULADO_A_NFE_02 LEFT OUTER JOIN
             fisc.TB_PAGAMENTOS_TRANSPORTAROS_OUTRAS_UF ON fisc.TB_217_PR_XML_CTE_PROPRIOS_E_TERCEIROS_VINCULADO_A_NFE_02.CTE_CHCTE = fisc.TB_PAGAMENTOS_TRANSPORTAROS_OUTRAS_UF.Chave_de_Acesso RIGHT OUTER JOIN
             fisc.TB_201_PR_XML_NOTAS_FISCAIS_PROPRIAS_E_TERCEIROS_01 ON fisc.TB_217_PR_XML_CTE_PROPRIOS_E_TERCEIROS_VINCULADO_A_NFE_02.NF_CHAVE_ACESSO = fisc.TB_201_PR_XML_NOTAS_FISCAIS_PROPRIAS_E_TERCEIROS_01.NF_CHAVE_ACESSO
WHERE (fisc.TB_201_PR_XML_NOTAS_FISCAIS_PROPRIAS_E_TERCEIROS_01.NF_CPF_CNPJ_DESTINATARIO <> '02357659000125') AND (fisc.TB_201_PR_XML_NOTAS_FISCAIS_PROPRIAS_E_TERCEIROS_01.NF_SITUACAO = 'A - AUTORIZADA DENTRO DO PRAZO') AND 
             (fisc.TB_217_PR_XML_CTE_PROPRIOS_E_TERCEIROS_VINCULADO_A_NFE_02.CTE_CPF_CNPJ_TOMADOR = N'02357659000125') AND (fisc.TB_217_PR_XML_CTE_PROPRIOS_E_TERCEIROS_VINCULADO_A_NFE_02.CTE_SITUACAO <> '1 - CANCELADA') AND 
             (fisc.TB_217_PR_XML_CTE_PROPRIOS_E_TERCEIROS_VINCULADO_A_NFE_02.CTE_UF_EMIT <> N'pb')