USE [933000081200000173202662_20260127_104141]
GO

/****** Objeto:  Table [dbo].[ITEM_NFE]    Data do Script: 20/07/2026 22:17:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ITEM_NFE](
	[sqitemnfe] [bigint] IDENTITY(1,1) NOT NULL,
	[sqnfe] [bigint] NOT NULL,
	[tpnfe] [int] NULL,
	[cdcfop] [int] NULL,
	[cdcst] [int] NULL,
	[cdcstcofins] [int] NULL,
	[cdcstipi] [int] NULL,
	[cdean] [nvarchar](14) NULL,
	[cdeantrib] [nvarchar](14) NULL,
	[cdcest] [varchar](10) NULL,
	[cdbenef] [varchar](10) NULL,
	[cdextipi] [int] NULL,
	[cdnve] [varchar](10) NULL,
	[cdmotdesicms] [int] NULL,
	[cdncm] [varchar](10) NULL,
	[cdclasseenqipi] [varchar](5) NULL,
	[cdselo] [varchar](60) NULL,
	[cdenqipi] [varchar](3) NULL,
	[cdopsn] [int] NULL,
	[cdproduto] [nvarchar](60) NULL,
	[cdcstpis] [int] NULL,
	[dsproduto] [nvarchar](255) NULL,
	[dsinfoadicprod] [varchar](3000) NULL,
	[idescala] [char](1) NULL,
	[idtotprod] [int] NULL,
	[nrcnpjfab] [varchar](14) NULL,
	[nritemnfe] [int] NULL,
	[nritempedidocomp] [int] NULL,
	[nrfci] [nvarchar](50) NULL,
	[nrpedidocomp] [varchar](15) NULL,
	[nrperccredsn] [decimal](16, 2) NULL,
	[nrperdif] [decimal](7, 4) NULL,
	[nrpercbcpropria] [decimal](16, 2) NULL,
	[nrpercredbcst] [decimal](16, 2) NULL,
	[nrpercmvast] [decimal](16, 2) NULL,
	[nrpercmercdev] [decimal](5, 2) NULL,
	[nrorigemprod] [int] NULL,
	[nrrecopi] [varchar](20) NULL,
	[nrcnpjprod] [varchar](14) NULL,
	[qtselo] [numeric](12, 0) NULL,
	[qtprodtrib] [decimal](16, 3) NULL,
	[qtprodcom] [decimal](16, 3) NULL,
	[qtunidipi] [decimal](16, 4) NULL,
	[qtbcpis] [decimal](16, 4) NULL,
	[qtbccofins] [decimal](16, 4) NULL,
	[sgufst] [nvarchar](2) NULL,
	[sgunidcom] [nvarchar](6) NULL,
	[sgunidtrib] [nvarchar](6) NULL,
	[tpmodbcicms] [int] NULL,
	[tpmodicmsst] [int] NULL,
	[vlaliqicms] [decimal](16, 2) NULL,
	[vlaliqicmsst] [decimal](16, 2) NULL,
	[vlaliqipi] [decimal](16, 2) NULL,
	[vlaliqpis] [decimal](16, 2) NULL,
	[vlaliqreducao] [decimal](16, 2) NULL,
	[vlaliqcfst] [decimal](7, 4) NULL,
	[vlaliqfcpstret] [decimal](10, 4) NULL,
	[vlaliqicmsefet] [decimal](10, 4) NULL,
	[vlaliqredbcefet] [decimal](10, 4) NULL,
	[vlbcipi] [decimal](16, 2) NULL,
	[vlbasecalcicms] [decimal](16, 2) NULL,
	[vlbasecalcicmsst] [decimal](16, 2) NULL,
	[vlbcstret] [decimal](16, 2) NULL,
	[vlbcstretdest] [decimal](16, 2) NULL,
	[vlbcfcpstret] [decimal](16, 2) NULL,
	[vlbcefet] [decimal](16, 2) NULL,
	[vlcredicmssn] [decimal](16, 2) NULL,
	[vldespacessoria] [decimal](16, 2) NULL,
	[vldesconto] [decimal](16, 2) NULL,
	[vlfrete] [decimal](16, 2) NULL,
	[vlfcpstret] [decimal](16, 2) NULL,
	[vlicms] [decimal](16, 2) NULL,
	[vlicmsdeson] [decimal](16, 2) NULL,
	[vlicmsdif] [decimal](16, 2) NULL,
	[vlicmsefet] [decimal](16, 2) NULL,
	[vlicmsoper] [decimal](16, 2) NULL,
	[vlicmsst] [decimal](16, 2) NULL,
	[vlicmsstretdest] [decimal](16, 2) NULL,
	[vlicmsstret] [decimal](16, 2) NULL,
	[vlicmssubst] [decimal](16, 2) NULL,
	[vlipi] [decimal](16, 2) NULL,
	[vlipidev] [decimal](16, 2) NULL,
	[vlproduto] [decimal](16, 2) NULL,
	[vlprodcom] [decimal](16, 2) NULL,
	[vlprodtrib] [decimal](16, 2) NULL,
	[vlseguro] [decimal](16, 2) NULL,
	[vltotaltributo] [decimal](16, 2) NULL,
	[vlunidipi] [decimal](16, 4) NULL,
	[vlbcpis] [decimal](16, 2) NULL,
	[vlpercaliqpis] [decimal](7, 4) NULL,
	[vlpis] [decimal](16, 2) NULL,
	[vlaliqprodpis] [decimal](16, 4) NULL,
	[vlbccofins] [decimal](16, 2) NULL,
	[vlpercaliqcofins] [decimal](7, 4) NULL,
	[vlcofins] [decimal](16, 2) NULL,
	[vlaliqcofins] [decimal](16, 2) NULL,
	[vlaliqprodcofins] [decimal](16, 4) NULL,
	[vlpercfcp] [decimal](16, 2) NULL,
	[vlfcp] [decimal](16, 2) NULL,
	[vlbcfcp] [decimal](16, 2) NULL,
	[vlpercfcpst] [decimal](16, 2) NULL,
	[vlfcpst] [decimal](16, 2) NULL,
	[vlbcfcpst] [decimal](16, 2) NULL,
 CONSTRAINT [PK_ITEMNF] PRIMARY KEY CLUSTERED 
(
	[sqitemnfe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ITEM_NFE]  WITH CHECK ADD CHECK  (([tpnfe]=(3) OR [tpnfe]=(2) OR [tpnfe]=(1)))
GO


